version: '3.3'

services:
    apache2-event:
        depends_on:
            - php-fpm
        build:
            context: ./apache2-event
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: "no"
        volumes:
            - ./sites/sites-document/:/var/www/html/
            - ./sites/sites-conf/:/usr/local/apache2/sites-conf/
            - ./logs/apache2/:/var/log/apache2/
    php-fpm:
        depends_on:
            - db
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        restart: "no"
        volumes:
            - ./sites/sites-document/:/var/www/html/
        user: 1000:1000
    db:
        image: mysql:5.7
        volumes:
            - ./mysql-db-storage:/var/lib/mysql
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: damp-mysql-database-root-password
